/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.studio.pci.circleimageview;

public final class R {
    public static final class attr {
        public static final int civ_border_color = 0x7f020049;
        public static final int civ_border_overlay = 0x7f02004a;
        public static final int civ_border_width = 0x7f02004b;
        public static final int civ_circle_background_color = 0x7f02004c;
        public static final int civ_fill_color = 0x7f02004d;
    }
    public static final class styleable {
        public static final int[] CircleImageView = { 0x7f020049, 0x7f02004a, 0x7f02004b, 0x7f02004c, 0x7f02004d };
        public static final int CircleImageView_civ_border_color = 0;
        public static final int CircleImageView_civ_border_overlay = 1;
        public static final int CircleImageView_civ_border_width = 2;
        public static final int CircleImageView_civ_circle_background_color = 3;
        public static final int CircleImageView_civ_fill_color = 4;
    }
}
